/**
 * Wire protocol shared between the Even Hub glasses app and the assistant server.
 *
 * Everything here is JSON-serialisable. Timestamps are ISO-8601 strings with an
 * explicit offset so the glasses never have to guess a timezone.
 */

/* ------------------------------------------------------------------ *
 * Pairing
 * ------------------------------------------------------------------ */

export interface PairStartRequest {
  /** Stable per-install identifier generated by the glasses app. */
  deviceId: string;
  /** Even Hub account display name, when the bridge exposes one. */
  deviceLabel?: string;
}

export interface PairStartResponse {
  pairingCode: string;
  /** Open this on a phone/desktop browser to complete Google sign-in. */
  verificationUrl: string;
  expiresAt: string;
  /** Suggested poll interval in milliseconds. */
  pollIntervalMs: number;
}

export type PairStatus = 'pending' | 'linked' | 'expired';

export interface PairPollResponse {
  status: PairStatus;
  /** Present once `status === 'linked'`. Send as `Authorization: Bearer <token>`. */
  sessionToken?: string;
  account?: AccountSummary;
}

export interface AccountSummary {
  email: string;
  name?: string;
  picture?: string;
  /** IANA timezone of the user's primary Google Calendar. */
  timeZone: string;
  scopes: string[];
}

/* ------------------------------------------------------------------ *
 * Assistant modes
 * ------------------------------------------------------------------ */

/**
 * `fast` answers from the user's own data only — calendar, mail, bookings,
 * location. `deep` additionally gives Claude the server-side web search and
 * web fetch tools, so it can read the open internet before answering.
 */
export type AssistantMode = 'fast' | 'deep';

export const ASSISTANT_MODES: readonly AssistantMode[] = ['fast', 'deep'];

/** A page the answer was actually built from, surfaced so claims are checkable. */
export interface SourceRef {
  title: string;
  url: string;
  /** Hostname alone — the HUD has no room for a full URL. */
  host: string;
}

/* ------------------------------------------------------------------ *
 * Bookings
 * ------------------------------------------------------------------ */

export const BOOKING_TYPES = [
  'hotel',
  'flight',
  'train',
  'bus',
  'car_rental',
  'restaurant',
  'event',
  'appointment',
  'delivery',
  'other',
] as const;

export type BookingType = (typeof BOOKING_TYPES)[number];

export interface BookingLocation {
  name?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
}

/**
 * A reservation extracted from an email. `start`/`end` are ISO-8601; when the
 * source email gave no timezone we fall back to the user's calendar timezone
 * and flag it via `timeZoneAssumed`.
 */
export interface Booking {
  id: string;
  type: BookingType;
  title: string;
  vendor?: string;
  confirmationCode?: string;
  start: string;
  end?: string;
  timeZone: string;
  timeZoneAssumed: boolean;
  location?: BookingLocation;
  /** Departure side of a journey (flight/train/bus). */
  origin?: BookingLocation;
  /** Arrival side of a journey. */
  destination?: BookingLocation;
  travellers?: number;
  price?: { amount: number; currency: string };
  notes?: string;
  cancellationPolicy?: string;
  /** Gmail message id this booking was extracted from. */
  sourceMessageId: string;
  sourceSubject?: string;
  sourceReceivedAt?: string;
  /** Google Calendar event id once synced. */
  calendarEventId?: string;
  /** 0..1 — the model's own confidence that this really is a reservation. */
  confidence: number;
  createdAt: string;
  updatedAt: string;
}

/* ------------------------------------------------------------------ *
 * Agenda
 * ------------------------------------------------------------------ */

export interface AgendaItem {
  id: string;
  title: string;
  start: string;
  end?: string;
  allDay: boolean;
  location?: string;
  /** Where this row came from, so the UI can mark synced bookings. */
  source: 'calendar' | 'booking';
  bookingType?: BookingType;
  calendarEventId?: string;
  /** Short human string like "in 2h 15m" computed server-side. */
  relative: string;
}

export interface AgendaResponse {
  timeZone: string;
  generatedAt: string;
  items: AgendaItem[];
}

/* ------------------------------------------------------------------ *
 * Assistant
 * ------------------------------------------------------------------ */

export interface ClientContext {
  /** Current phone location, when the user granted the permission. */
  location?: { latitude: number; longitude: number; accuracy?: number };
  /** IANA timezone reported by the WebView. */
  timeZone?: string;
  /** BCP-47 tag of the UI locale, used to pick the answer language. */
  locale?: string;
  battery?: number;
  isWearing?: boolean;
}

export interface AskRequest {
  /** Free-form user question. */
  text: string;
  /** Conversation id; omit to start a new thread. */
  conversationId?: string;
  context?: ClientContext;
  /** Overrides the account's saved mode for this one question. */
  mode?: AssistantMode;
}

export interface VoiceAskRequest {
  /** base64 of raw PCM: 16 kHz, signed 16-bit little-endian, mono. */
  audioBase64: string;
  sampleRate?: number;
  conversationId?: string;
  context?: ClientContext;
  mode?: AssistantMode;
}

/** One tool round-trip, surfaced so the glasses can show "Checking calendar…". */
export interface AssistantStep {
  tool: string;
  summary: string;
  ok: boolean;
  durationMs: number;
}

export interface AssistantAnswer {
  conversationId: string;
  /** What the user actually asked (transcript, for the voice path). */
  question: string;
  /** Plain text, already trimmed for a 576x288 display. */
  answer: string;
  steps: AssistantStep[];
  /** Structured rows worth rendering as a list instead of prose. */
  items?: AgendaItem[];
  /** Pages consulted on the web, when the question ran in `deep` mode. */
  sources?: SourceRef[];
  /** Model + usage, for debugging in the phone-side panel. */
  meta: {
    model: string;
    mode: AssistantMode;
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    webSearches: number;
    webFetches: number;
    latencyMs: number;
    truncated: boolean;
  };
}

/* ------------------------------------------------------------------ *
 * Account settings
 * ------------------------------------------------------------------ */

export interface AccountState {
  account: AccountSummary;
  lastGmailSyncAt?: string;
  bookings: number;
  voiceEnabled: boolean;
  /** The account's default mode for new questions. */
  mode: AssistantMode;
  /** Whether this account has its own Anthropic key on file. */
  hasOwnApiKey: boolean;
  /** Last four characters of that key, for recognising which one is stored. */
  apiKeyHint?: string;
  /** False when neither a personal nor a server key is available. */
  assistantReady: boolean;
}

export interface SetApiKeyRequest {
  /** An `sk-ant-…` key. Validated against the Anthropic API before it is stored. */
  apiKey: string;
}

/* ------------------------------------------------------------------ *
 * Notifications
 * ------------------------------------------------------------------ */

export type NotificationKind =
  | 'booking_reminder'
  | 'booking_added'
  | 'agenda_change'
  | 'leave_now'
  | 'system';

export interface AssistantNotification {
  id: string;
  kind: NotificationKind;
  title: string;
  body: string;
  createdAt: string;
  /** When the glasses should stop showing it. */
  expiresAt?: string;
  bookingId?: string;
  calendarEventId?: string;
}

export type StreamEvent =
  | { type: 'ready'; account: AccountSummary }
  | { type: 'notification'; notification: AssistantNotification }
  | { type: 'agenda'; agenda: AgendaResponse }
  | { type: 'ping'; at: string };

/* ------------------------------------------------------------------ *
 * Sync
 * ------------------------------------------------------------------ */

export interface SyncResult {
  scannedMessages: number;
  newBookings: number;
  updatedBookings: number;
  calendarEventsWritten: number;
  skipped: number;
  errors: string[];
  startedAt: string;
  finishedAt: string;
}

export interface ApiError {
  error: string;
  message: string;
  /** Set when the session token is dead and the app must re-pair. */
  reauth?: boolean;
}
